<?php
	class WPVV_WC_Field extends WPVV_Record {
		public $type = 'wpvv_wcf';
		
		public $wooMainFields = [
			'billing_first_name',
			'billing_last_name',
			'billing_company',
			'billing_country',
			'billing_address_1',
			'billing_address_2',
			'billing_city',
			'billing_state',
			'billing_postcode',
			'billing_phone',
			'billing_email',
			'shipping_first_name',
			'shipping_last_name',
			'shipping_company',
			'shipping_country',
			'shipping_address_1',
			'shipping_address_2',
			'shipping_city',
			'shipping_state',
			'shipping_postcode',
			'order_comments',
		];
		
		public function getAll( $filters = [], $orderBy = 'menu_order', $orderByDirection = 'ASC', $extraArgs = [] ) {
			return parent::getAll( $filters, $orderBy, $orderByDirection, $extraArgs ); // TODO: Change the autogenerated stub
		}
		
		public function getSection($section){
			$meta_query = 				[
				'key'     => 'section',
				'value'   => $section,
				'compare' => '=',
			];
			
			return $this->getAll($meta_query, 'menu_order', 'ASC');
		}
		
		public function isWooMainField($field){
			return in_array($field->post_name, $this->wooMainFields);
		}
		
		public function isPostMetaField($field){
			return !$this->isWooMainField($field) && $field->meta && $field->meta['metaType'] === 'post';
		}
		public function isUserMetaField($field){
			return !$this->isWooMainField($field) && $field->meta && $field->meta['metaType'] === 'user';
		}
		public function isDisabled($field){
			return $field->meta['disabled'] == 1;
		}
	}
	
	$GLOBALS['WPVV_WC_Field'] = new WPVV_WC_Field();