<?php
	class WPV_WC_Field extends WPV_Record {
		public $type = 'wpv_wcf';
		
		public function getAll( $filters = [], $orderBy = 'menu_order', $orderByDirection = 'ASC', $extraArgs = [] ) {
			return parent::getAll( $filters, $orderBy, $orderByDirection, $extraArgs ); // TODO: Change the autogenerated stub
		}
		
		public function getSection($section){
			$meta_query = 				[
				'key'     => 'section',
				'value'   => $section,
				'compare' => '=',
			];
			
			return $this->getAll($meta_query, 'menu_order', 'ASC');
		}
	}
	
	$GLOBALS['WPV_WC_Field'] = new WPV_WC_Field();